source: src
destination: app
title: Lingen Grunnboring AS
timezone: Europe/Oslo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Vi er et lite firma med høy kompetanse, som har som mål å være ledende innen kvalitet i utført arbeid. 
  Vi tilbyr tjenester innen geotekniske grunnundersøkelser og har pr i dag to borerigger. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
logo: /assets/img/logo.png

excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: assets/_sass
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
# exclude: ['assets/sass']


collections:
  references:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "references"
    values:
      layout: "pages/pageWithCarousel"


