source: src
destination: app
title: Lingen Grunnboring
timezone: Europe/Oslo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
logo: /assets/img/logo.png

excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: assets/_sass
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
# exclude: ['assets/sass']


collections:
  references:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "references"
    values:
      layout: "pages/pageWithCarousel"


